name: rubocop

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Code style check

    container:
      image: ruby:2.6.8-buster

    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: Install rubocop
        run: gem install rubocop -v 0.81.0

      - name: Rubocop
        run: rubocop
