name: spec
on: push

jobs:
  spec:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Ruby, run bundle install and cache the gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.7
          bundler-cache: true

      - name: Run tests
        run: bundle exec rspec
